### ISSUE TITLE
Websocket server online tester

### ISSUE THREAD

**Issue by pestsov-v** [asyncapi/nodejs-ws-template#269]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement? - Userfrendly functionality 
- How will this change help? - Add more popularity of community and create clear usefull experience
- What is the motivation? - Not to be a reader, but to be a tester.

#### Description
Please try answering few of those questions
- What changes have to be introduced? - Add the Websocket server online tester.
- Will this be a breaking change? - No. This is new feature.
- How could it be implemented/designed? - 
1. Add server instance which works into some host and port (may be add this paramaters to YAML / JSON configuration for servers block).
2. This server instanse conevert this JSON schema object (documentation) end convert this to routines. This routines can be execute (like as SwaggerAPI). 
3. Add mock data block into parameters / payload and etc. Then this blocks are parse and implement into server routines. When documentator descripe event, then him can be execute routine with this fake (mock) data and tested this route.  

P.S. This event driven server need to union base server url with event description. 

This serve may be is killer fueture for your lib. Thanks for Attention.

example: https://livepersoninc.github.io/ws-test-page/

**Comment by derberg** [comment]
@pestsov-v hey thanks for the idea, I have some followup questions

> Add server instance which works into some host and port 

you mean basically host online somewhere app generated from this template. Like https://github.com/derberg/shrekapp-asyncapi-designed ?

> This server instanse conevert this JSON schema object (documentation) end convert this to routines. This routines can be execute (like as SwaggerAPI).

I don't get what `this JSON schema` are you referring to and what `routines` you have in mind. Also not sure what are you referring to as `SwaggerAPI`

> Add mock data block into parameters / payload and etc. Then this blocks are parse and implement into server routines. When documentator descripe event, then him can be execute routine with this fake (mock) data and tested this route

sorry don't get it

---
why is this needed, why not just use https://livepersoninc.github.io/ws-test-page/ and `wss://ws.postman-echo.com/raw`
