### ISSUE TITLE
This template is not compatible with the current version of the generator

### ISSUE THREAD

**Issue by armensanoyan** [asyncapi/nodejs-ws-template#408]
### Describe the bug.

when running generation get this error

    Error: This template is not compatible with the current version of the generator (2.5.0). This template is compatible with the following version range: >=0.50.0 <2.0.0.
    at isTemplateCompatible (/opt/homebrew/lib/node_modules/@asyncapi/generator/lib/templateConfigValidator.js:57:11)
    at module.exports.validateTemplateConfig (/opt/homebrew/lib/node_modules/@asyncapi/generator/lib/templateConfigValidator.js:30:3)
    at Generator.configureTemplateWorkflow (/opt/homebrew/lib/node_modules/@asyncapi/generator/lib/generator.js:311:5)
    at async Generator.generate (/opt/homebrew/lib/node_modules/@asyncapi/generator/lib/generator.js:199:5)
    at async Generator.generateFromURL (/opt/homebrew/lib/node_modules/@asyncapi/generator/lib/generator.js:473:12)
    
 And here is the exact command I run
    
    ag https://raw.githubusercontent.com/asyncapi/generator/v1.4.0/test/docs/ws.yml @asyncapi/nodejs-ws-template -o output -p server=localhost

In case of downgrading to 1.10.0 it runned the generation, but I suppose it should work on version 2.5.0 too. I tried to run the same command for 2.5.0 version  too like so

    ag https://raw.githubusercontent.com/asyncapi/generator/v2.5.0/test/docs/ws.yml @asyncapi/nodejs-template -o output -p server=localhost

it didn't work again. But this time got an other error

    Something went wrong:
    Error: Input is not a corrent AsyncAPI document so it cannot be processed.
        at Generator.generateFromString (/opt/homebrew/lib/node_modules/@asyncapi/generator/lib/generator.js:264:19)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async /opt/homebrew/lib/node_modules/@asyncapi/generator/cli.js:159:9
    Errors:
    [
      {
        "code": "asyncapi-is-asyncapi",
        "message": "This is not an AsyncAPI document. The \"asyncapi\" field as string is missing.",
        "path": [],
        "severity": 0,
        "source": "https://raw.githubusercontent.com/asyncapi/generator/v2.5.0/test/docs/ws.yml",
        "range": {
          "start": {
            "line": 0,
            "character": 0
          },
          "end": {
            "line": 0,
            "character": 14
          }
        }
      },
      {
        "code": "parser",
        "message": "Mapping key must be a string scalar rather than number",
        "severity": 0,
        "path": [
          "404"
        ],
        "range": {
          "start": {
            "line": 0,
            "character": 0
          },
          "end": {
            "line": 0,
            "character": 3
          }
        },
        "source": "https://raw.githubusercontent.com/asyncapi/generator/v2.5.0/test/docs/ws.yml"
      }
    ]

### Expected behavior

Please provide working cli command to run generation. 

### Screenshots

<img width="1301" alt="Screenshot 2024-11-13 at 12 08 00" src="https://github.com/user-attachments/assets/95b9f731-7fce-465d-8f40-a591c384ef83">

### How to Reproduce

1. `npm install -g @asyncapi/generator`
2. `ag https://raw.githubusercontent.com/asyncapi/generator/v1.4.0/test/docs/ws.yml @asyncapi/nodejs-ws-template -o output -p server=localhost`

### 🥦 Browser

None

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by derberg** [comment]
Hi, it might work with newer generator but that has to be checked. Please open a PR and change https://github.com/asyncapi/nodejs-ws-template/blob/master/package.json#L89 value from `2.0.0` to `3.0.0`

keep in mind node 18 minimum is required

**Comment by armensanoyan** [comment]
Hey thanks for replay. Do I need any permission to push a new branch?
