### ISSUE TITLE
Add support for params

### ISSUE THREAD

**Issue by aayushmau5** [asyncapi/nodejs-ws-template#77]
#### Describe the bug
Currently, websockets doesn't support parameters, so generating code for the following AsyncAPI document won't work. 
```
channels:
  message/{user1Id}/{user2Id}:
    parameters:
      user1Id:
        description: Id of the first user.
        schema:
          type: string
      user2Id:
        description: Id of the second user.
        schema:
          type: string
    subscribe:
      operationId: subChat
      message:
        $ref: "#/components/messages/chat"
    publish:
      operationId: pubChat
      message:
        $ref: "#/components/messages/chat"
```

#### How to Reproduce
For the above AsyncAPI document, the generated code will have the following file in `services` directory

![Screenshot_2021-05-06_23 27 59](https://user-images.githubusercontent.com/54525741/117352911-278cce00-aecd-11eb-98f0-97fb16d04e1e.png)

Which doesn't match the file name used in require statement
![Screenshot_2021-05-06_23 29 23](https://user-images.githubusercontent.com/54525741/117353096-560aa900-aecd-11eb-8f0d-ca1b3f3d247a.png)

#### Expected behavior
The template should've the correct file name in the `require` statement. Like, 
```
const { subChat, pubChat } = require('./services/message-{user1Id}-{user2Id}.js');
```

**Comment by derberg** [comment]
I noticed it when I worked on Shrek and travel/status and was thinking about adding a param where you can provide destination name. Didn't have time to focus on the fix back then. This is a big issue of this template + lack of support for multiple messages (another issue). 

I was just thinking that maybe it's better to first rewrite the template to React render engine to not invest too much in Nunjucks

**Comment by aayushmau5** [comment]
> I was just thinking that maybe it's better to first rewrite the template to React render engine to not invest too much in Nunjucks

I think so too. I mean we can just still use Nunjucks to provide params but I think that using React render will we more "modern" approach.
